config-diff: be more accurate when barfing if passed files are wrong in restricted mode
Signed-off-by: Franck Bui-Huu <fbuihuu@gmail.com>

diff --git a/kdist-config--diff b/kdist-config--diff
--- a/kdist-config--diff
+++ b/kdist-config--diff
@@ -31,11 +31,13 @@ do
 done
 
 #
-# Sort out the config files to compare
+# Sort out the config files to compare. When running in restricted
+# mode the 2 passed arguments are always files (case 2.b).
 #
-#     0: .config <-> <pattern>
-#     1: .config <-> <pattern>|<file>
-#     2: <pattern>|<file> <-> <pattern>|<file>
+#     0   : .config <-> <pattern>
+#     1   : .config <-> <pattern>|<file>
+#     2.a : <pattern>|<file> <-> <pattern>|<file>
+#     2.b : <file> <-> <file>
 #
 case $# in
 0|1)
@@ -54,11 +56,21 @@ case $# in
 	;;
 2)
 	two=$2
-	test -e "$two" || two=$(config__resolve_files --fullpath "$2") || exit
+	if ! test -e "$two"; then
+		case $KDIST_RESTRICTED_MODE in
+		yes)	die "file '$two' not found." ;;
+		no)	two=$(config__resolve_files --fullpath "$2") || exit
+		esac
+	fi
 	;&
 1)
 	one=$1
-	test -e "$one" || one=$(config__resolve_files --fullpath "$1") || exit
+	if ! test -e "$one"; then
+		case $KDIST_RESTRICTED_MODE in
+		yes)	die "file '$one' not found." ;;
+		no)	one=$(config__resolve_files --fullpath "$1") || exit
+		esac
+	fi
 	;;
 *)
 	kdist__usage
